spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: false

#    properties:
#      hibernate:
#        show_sql: true

logging:
  level:
    root: info