spring:
  datasource:
    username: washindeiru
    password: aha321
    url: jdbc:postgresql://localhost/electronics

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
#    properties:
#      hibernate:
#        show_sql: true
logging:
  level:
    root: info
